### ISSUE TITLE
Evaluate external clock

### ISSUE THREAD

**Issue by stan23** [stan23/HM-ES-PMSw1-Pl_GosundSP1#4]
The current, voltage, power measurements are quite inaccurate.

Maybe it is advised to mount an external clock generator and don't use the internal oscillator?

**Comment by pa-pa** [comment]
I also think an external crystal will improve the measured values.

**Comment by stan23** [comment]
I'm wondering whether the 0.5% of https://www.reichelt.de/smd-resonator-8-00-mhz-groesse-3-2x1-3x0-9mm-cstce-8-00-p89701.html are sufficient.

**Comment by stan23** [comment]
Wenn ich bei Reichelt schaue, finde ich folgendes:

Resonator:
[CSTCE 8,00](https://www.reichelt.de/smd-resonator-8-00-mhz-groesse-3-2x1-3x0-9mm-cstce-8-00-p89701.html)
Maße: 3,2x1,3x0,9mm
Frequenztoleranz: ± 0,5 %
Preis: 0,31 Euro

Quarz:
[8,000000-MQ](https://www.reichelt.de/keramik-smd-quarz-5x7x1-2mm-8-0-mhz-8-000000-mq-p84989.html?)
Maße: 5,0 x 7,0 x 1,2 mm
Frequenztoleranz: ± 30 ppm
Preis: 0,83 Euro
Benötigt zwei zusätzliche Kondensatoren mit 22 pF!

Quarzoszillator:
[XO32 8,00000](https://www.reichelt.de/quarzoszillator-keramik-smd-xo32-8-0-mhz-xo32-8-00000-p101055.html?)
Maße: 2,5 x 3,2 x 0,95 mm
Frequenzstabiliät: +-50ppm
Preis: 1,40 Euro


Ich denke der Quarz scheidet wegen der Größe aus.


Hintergrundinformationen:
[AVR-Tutorial](https://www.mikrocontroller.net/articles/AVR-Tutorial:_Equipment#Erg.C3.A4nzende_Hinweise_zur_Taktversorgung_.28kann_.C3.BCbersprungen_werden.29)

**Comment by pa-pa** [comment]
Ich denke der "einfache" Resonator ist ausreichend, da er schon um Faktor 5-10 besser ist als der interne. Außerdem ist er nicht so Temperatur abhängig.
Vielleicht kann man ja mal einen mit Draht anlöten und sehen, ob sich das Verhalten wesentlich verbessert. Die Dinger sind doch auf dem China-Pro-Minis drauf.

**Comment by jp112sdl** [comment]
Bei meinem Testaufbau mit internem Takt erhalte ich jetzt gleichmäßig saubere Werte.
Eine angeschlossene ohmsche Last (Glühlampe) von 40W wird bei mir fast immer mit 40W erfasst, in seltenen Fällen mal mit 39W oder 41W. Ich denke mal, besser wird es nicht gehen.

Ein ext. Takt kann m.M. nach aber nicht schaden.
Gerade beim seriellen Debug sieht man doch recht häufig Schrottzeichen.

Werde heute mal mit einem Reso vom Pro Mini testen (wenn ich es löttechnisch auf die Reihe bekomme).

**Comment by jp112sdl** [comment]
1x schmunzeln 😄 So sieht mein Testaufbau aus:

![img_8989](https://user-images.githubusercontent.com/18190139/47949647-1ef75d80-df47-11e8-8e24-2a2839afe626.jpg)

Habe die Fuse auf ext 8MHz gestellt (low fuse = 0xff).
Die seriellen Ausgaben kommen nun fehlerfrei.
An der Messung hat sich nichts geändert - aber die war bei mir ja auch schon vorher top.

Wie man den Reso mit nem Lötkolben auf die Platine bekommt, weiß ich nicht.
Dafür fehlt mir die SMD-Löterfahrung. Seitlich ist nur minimal Lötfläche vorhanden.

**Comment by stan23** [comment]
Sehr schick :smile:
Wie hast du den Resonator denn runter bekommen? Ich denke wenn die Pads etwas länger sind geht das schon mit dem Lötkolben.
Diese Platine ist übrigens mit Heißluft gelötet, die no-clean-Paste hinterlässt diese ekligen gelben harten Rückstände...

**Comment by jp112sdl** [comment]
> Wie hast du den Resonator denn runter bekommen? 

Hab ihn in einem dicken Tropfen Zinn getränkt, dann ist er von selbst von der Platine gerutscht. 🤓 

> die no-clean-Paste hinterlässt diese ekligen gelben harten Rückstände...

Function first! 👍 Sieht man ja nicht. Ist im geschlossenen Gehäuse. _(sollte zumindest so sein ;))_

**Comment by stan23** [comment]
Ich habe einen Resonator in die Platine eingefügt :)

**Comment by jp112sdl** [comment]
Super!
_P.S.: dann müsste in der README noch die low-Fuse auf 0xff geändert werden_

**Comment by stan23** [comment]
fixed in V1.0
